export interface Tag {
  id: string
  name: string
  color: string
  icon?: string
  parentId?: string
  autoGenerated: boolean
  usageCount: number
  createdAt: Date
  children?: Tag[]
}

export interface TagFilter {
  include: string[]
  exclude: string[]
}
